linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell

linters-settings:
  goimports:
    local-prefixes: github.com/dotbrains/gh-identity

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
