version: 2

builds:
  - id: gh-identity
    main: ./cmd/gh-identity
    binary: gh-identity
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

  - id: gh-identity-hook
    main: ./cmd/gh-identity-hook
    binary: gh-identity-hook
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: gh-identity-archive
    ids:
      - gh-identity
      - gh-identity-hook
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

homebrew_casks:
  - name: gh-identity
    ids:
      - gh-identity-archive
    repository:
      owner: dotbrains
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    homepage: https://github.com/dotbrains/gh-identity
    description: "Multi-account GitHub identity management — automatic context-based account switching and per-directory identity binding."
    license: MIT
    skip_upload: auto
    url:
      verified: github.com/dotbrains/gh-identity
    binaries:
      - gh-identity
      - gh-identity-hook
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gh-identity"]
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gh-identity-hook"]
          end

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
